# Changes here will be overwritten by Copier
_commit: 3d9a86d
_src_path: https://github.com/python-project-templates/base.git
add_extension: rust
email: t.paine154@gmail.com
github: timkpaine
project_description: Atomic Counters
project_name: atomic counter
python_version_primary: '3.11'
team: the atomic-counter authors
