# Changes here will be overwritten by Copier
_commit: 74b8054
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: rust
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Atomic Counters
project_name: atomic counter
python_version_primary: '3.11'
team: the atomic-counter authors
